### ISSUE TITLE
Error: jsonschema.exceptions.ValidationError: Invalid schema

### ISSUE THREAD

**Issue by pzelnip** [kiwicom/schemathesis#610] opened 2020-06-04 16:38 UTC
I'm getting Invalid Schema running against the Swagger 2.0 spec for a project I work on.  The swagger can be found at https://dev-onboardingapi.na.bambora.com/v1/boarding/swagger/2016-08-18

The same Swagger is accepted without error in the Live Demo editor at Swagger.io (https://editor.swagger.io/)  (ie if I copy the swagger data at that URL and paste into the editor at Swagger.io it reports no errors).

However, schemathesis is saying it's an invalid schema, and the --show-errors-tracebacks only seems to indicate there's a typeerror somewhere that gets encountered:

```
$ schemathesis run https://dev-onboardingapi.na.bambora.com/v1/boarding/swagger/2016-08-18 --show-errors-tracebacks
An internal error happened during a test run
Error: Traceback (most recent call last):
  File "/Users/pzelnip/.virtualenvs/schemathesis/lib/python3.8/site-packages/schemathesis/loaders.py", line 160, in _maybe_validate_schema
    jsonschema.validate(instance, schema)
  File "/Users/pzelnip/.virtualenvs/schemathesis/lib/python3.8/site-packages/jsonschema/validators.py", line 932, in validate
    error = exceptions.best_match(validator.iter_errors(instance))

... many lines ...

  File "/Users/pzelnip/.virtualenvs/schemathesis/lib/python3.8/site-packages/jsonschema/_utils.py", line 98, in find_additional_properties
    if patterns and re.search(patterns, property):
  File "/Users/pzelnip/.pyenv/versions/3.8.2/lib/python3.8/re.py", line 199, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/pzelnip/.virtualenvs/schemathesis/lib/python3.8/site-packages/schemathesis/runner/__init__.py", line 163, in execute_from_schema
    schema = load_schema(

... many lines ...

  File "/Users/pzelnip/.virtualenvs/schemathesis/lib/python3.8/site-packages/schemathesis/loaders.py", line 162, in _maybe_validate_schema
    raise ValidationError("Invalid schema") from exc
jsonschema.exceptions.ValidationError: Invalid schema

Add this option to your command line parameters to see full tracebacks: --show-errors-tracebacks

You can disable input schema validation with --validate-schema=false command-line option
In this case, Schemathesis can not guarantee proper behavior during the test run
```

I'm rather puzzled what the error is, or what part of my schema would be producing it (ie what part is invalid).

In case it matters:

Python version 3.8.2
Schemathesis version: 1.7.0

**Comment by Stranger6667** [comment] 2020-06-04 18:38
Hi @pzelnip !

Thank you for reporting this! I assume that the problem is that inside the schema the status codes for responses are integers but should be strings according to the spec and `jsonschema` can't handle validation correctly.

Similar issue - https://github.com/kiwicom/schemathesis/issues/513

I forgot to submit a bug report upstream to `jsonschema` :( so the error is more clear

**Comment by Stranger6667** [comment] 2020-07-15 20:37
Closing this issue, since the schema provided doesn't comply with the spec - the HTTP status codes should be strings. It is not noted specifically in the Open API, but the relevant JSON Schema has `patternProperties` keyword to describe it and this keyword can be applied only to strings because JSON spec requires object keys to be strings. The problem is with YAML, that has a lot of implicit conversions and apparently that Swagger.io is less strict on this matter (however all the examples they have contain HTTP codes as strings) and accept such YAML document. I suggest converting all these codes to strings in the schema or using `--validate-schema=false` in the CLI. 
Our policy is being as close to the strict schema compliance as possible with optional disabling of certain checks (e.g. the `--validate-schema` option or fixups for FastAPI). I'll create an issue in `jsonschema` shortly

**Closed by Stranger6667** 2020-07-15 20:37 UTC

**Comment by Stranger6667** [comment] 2020-07-15 21:09
And it was already discussed in `jsonschema` [here](https://github.com/Julian/jsonschema/pull/286).

In short - there were multiple PRs to improve these, but they were closed. The intend is that the input should be deserialized valid JSON, and any transformations should be done before passing it to `validate`, however, `pyyaml` implicitly allows it :/ Maybe it could be done with some more user-friendly message on the `jsonschema` side or `schemathesis` side
