### ISSUE TITLE
Using $ref causes schema parsing error

### ISSUE THREAD

**Issue by ArinCantCode** [kiwicom/schemathesis#418] opened 2020-02-11 16:18 UTC
I'm using Open api v3.

The issue occurs both using `yaml` and `json` representation of the spec.

My yaml:

```
openapi: "3.0.0"
info:
  description: |
    Some description
  version: "1.0.0"
  title: "This yaml is causing issues"
paths:
  "/s/stats/exchange":
    get:
      summary: "Gets currency exchange rates"
      operationId: "getCurrencyExchangeRates"
      responses:
        "200":
          description: "A JSON object with currency tag as key and rate as value"
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/CurrencyCode'
                
components:
  schemas:
    CurrencyCode:
      type: string
      minLength: 3
      maxLength: 3

```

I use swagger editor webpage to export my yaml into the json file and afterwards trying to test it by running command:

`schemathesis run ./swagger.yaml --base-url <base url goes here>`

And i receive an error:

```
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "c:\python38\lib\site-packages\jsonschema\_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 856, in resolve_remote
    result = self.handlers[scheme](uri)
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 36, in load_file
    with open(location) as fd:
FileNotFoundError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 190, in get_all_endpoints
    methods = self.resolve(methods)
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
    item[key] = self.resolve(sub_item)
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
    item[key] = self.resolve(sub_item)
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
    item[key] = self.resolve(sub_item)
  [Previous line repeated 4 more times]
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 285, in resolve
    with self.resolver.resolving(item["$ref"]) as resolved:
  File "c:\python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 754, in resolving
    url, resolved = self.resolve(ref)
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "c:\python38\lib\site-packages\jsonschema\validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: [Errno 2] No such file or directory: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\schemathesis.exe\__main__.py", line 7, in <module>
  File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python38\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python38\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python38\lib\site-packages\schemathesis\cli\__init__.py", line 231, in run
    execute(prepared_runner, workers_num, show_errors_tracebacks)
  File "c:\python38\lib\site-packages\schemathesis\cli\__init__.py", line 285, in execute
    handler(context, event)
  File "c:\python38\lib\site-packages\schemathesis\cli\output\default.py", line 318, in handle_event
    handle_initialized(context, event)
  File "c:\python38\lib\site-packages\schemathesis\cli\output\default.py", line 279, in handle_initialized
    click.secho(f"collected endpoints: {event.schema.endpoints_count}", bold=True)
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 86, in endpoints_count
    return len(list(self.get_all_endpoints()))
  File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 202, in get_all_endpoints
    raise InvalidSchema("Schema parsing failed. Please check your schema.")
schemathesis.exceptions.InvalidSchema: Schema parsing failed. Please check your schema.

```

The moment i don't use `$ref` and put the type directly where the response is, the issue is solved

**Comment by Stranger6667** [comment] 2020-02-11 16:21
Hello @ArinCantCode !

Thank you for your report :) I'll check the issue soon

**Comment by Stranger6667** [comment] 2020-02-11 16:58
Hm, could you share the output before the error stacktrace? It should contain version info. It might be connected with its work on Windows - it works on my Linux machine:

```
⇒  schemathesis run ./swagger.yaml --base-url=http://127.0.0.1:8081/
======================== Schemathesis test session starts =======================
platform Linux -- Python 3.8.1, schemathesis-0.23.7, hypothesis-5.5.1, hypothesis_jsonschema-0.11.1, jsonschema-3.2.0
rootdir: /tmp
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/tmp/.hypothesis/examples')
Schema location: /tmp/swagger.yaml
Base URL: http://127.0.0.1:8081/
Specification version: Open API 3.0.0
Workers: 1
collected endpoints: 1

GET /s/stats/exchange .                                                   [100%]

==================================== SUMMARY ====================================

not_a_server_error            1 / 1 passed          PASSED 

=============================== 1 passed in 0.01s ===============================
```

**Comment by ArinCantCode** [comment] 2020-02-11 17:17
Thanks for a quick response 👍 

Here is the output:

```
rootdir: C:\swagger-tooling
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('C:\\swagger-tooling\\.hypothesis\\examples')
Schema location: C:\swagger-tooling\swagger.json
Base URL: <base url>
Specification version: Open API 3.0.0
Workers: 1

```

**Comment by Stranger6667** [comment] 2020-02-11 17:23
Sorry for the inconvenience, I will look at it during this week - we'd like to setup CI builds on Windows (#401) soon and I need to have some dev environment as well. I'll let you know about the progress

**Comment by Jonke** [comment] 2020-02-13 12:03
A workaround for is to use prance[prance](https://pypi.org/project/prance/) to compile the yaml/json into a fully resolved json file that will work with schemathesis

**Comment by Jonke** [comment] 2020-02-13 12:07
> I'm using Open api v3.
> 
> The issue occurs both using `yaml` and `json` representation of the spec.
> 
> My yaml:
> 
> ```
> openapi: "3.0.0"
> info:
>   description: |
>     Some description
>   version: "1.0.0"
>   title: "This yaml is causing issues"
> paths:
>   "/s/stats/exchange":
>     get:
>       summary: "Gets currency exchange rates"
>       operationId: "getCurrencyExchangeRates"
>       responses:
>         "200":
>           description: "A JSON object with currency tag as key and rate as value"
>           content:
>             application/json:
>               schema:
>                 type: object
>                 additionalProperties:
>                   $ref: '#/components/schemas/CurrencyCode'
>                 
> components:
>   schemas:
>     CurrencyCode:
>       type: string
>       minLength: 3
>       maxLength: 3
> ```
> 
> I use swagger editor webpage to export my yaml into the json file and afterwards trying to test it by running command:
> 
> `schemathesis run ./swagger.yaml --base-url <base url goes here>`
> 
> And i receive an error:
> 
> ```
> Traceback (most recent call last):
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 774, in resolve_from_url
>     document = self.store[url]
>   File "c:\python38\lib\site-packages\jsonschema\_utils.py", line 22, in __getitem__
>     return self.store[self.normalize(uri)]
> KeyError: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 777, in resolve_from_url
>     document = self.resolve_remote(url)
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 856, in resolve_remote
>     result = self.handlers[scheme](uri)
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 36, in load_file
>     with open(location) as fd:
> FileNotFoundError: [Errno 2] No such file or directory: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 190, in get_all_endpoints
>     methods = self.resolve(methods)
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
>     item[key] = self.resolve(sub_item)
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
>     item[key] = self.resolve(sub_item)
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 288, in resolve
>     item[key] = self.resolve(sub_item)
>   [Previous line repeated 4 more times]
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 285, in resolve
>     with self.resolver.resolving(item["$ref"]) as resolved:
>   File "c:\python38\lib\contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 754, in resolving
>     url, resolved = self.resolve(ref)
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 766, in resolve
>     return url, self._remote_cache(url)
>   File "c:\python38\lib\site-packages\jsonschema\validators.py", line 779, in resolve_from_url
>     raise exceptions.RefResolutionError(exc)
> jsonschema.exceptions.RefResolutionError: [Errno 2] No such file or directory: ''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\python38\lib\runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\python38\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Python38\Scripts\schemathesis.exe\__main__.py", line 7, in <module>
>   File "c:\python38\lib\site-packages\click\core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\python38\lib\site-packages\click\core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "c:\python38\lib\site-packages\click\core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\python38\lib\site-packages\click\core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\python38\lib\site-packages\click\core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "c:\python38\lib\site-packages\schemathesis\cli\__init__.py", line 231, in run
>     execute(prepared_runner, workers_num, show_errors_tracebacks)
>   File "c:\python38\lib\site-packages\schemathesis\cli\__init__.py", line 285, in execute
>     handler(context, event)
>   File "c:\python38\lib\site-packages\schemathesis\cli\output\default.py", line 318, in handle_event
>     handle_initialized(context, event)
>   File "c:\python38\lib\site-packages\schemathesis\cli\output\default.py", line 279, in handle_initialized
>     click.secho(f"collected endpoints: {event.schema.endpoints_count}", bold=True)
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 86, in endpoints_count
>     return len(list(self.get_all_endpoints()))
>   File "c:\python38\lib\site-packages\schemathesis\schemas.py", line 202, in get_all_endpoints
>     raise InvalidSchema("Schema parsing failed. Please check your schema.")
> schemathesis.exceptions.InvalidSchema: Schema parsing failed. Please check your schema.
> ```
> 
> The moment i don't use `$ref` and put the type directly where the response is, the issue is solved

And, @Stranger6667, I can confirm that using a openapi3.json with $refs don't work  in schemathesis

**Comment by Stranger6667** [comment] 2020-02-13 12:17
> And, @Stranger6667, I can confirm that using a openapi3.json with $refs don't work in schemathesis

Does it occur also on Windows? or any other OS is affected as well?

At the moment @svtkachenko is working on the fix

**Comment by ArinCantCode** [comment] 2020-02-13 14:39
>Does it occur also on Windows? or any other OS is affected as well?

Following your comment:
>it works on my Linux machine:

i tried it myself using ubuntu subsystem on windows. It works there so i would assume the problem only occurs on windows.

**Comment by Stranger6667** [comment] 2020-02-13 14:44
The issue is related to different path separators in the handler that we have for json refs, hopefully, will be fixed soon

**Comment by Stranger6667** [comment] 2020-02-14 17:18
ok, we have builds on Windows now, the problem is that inside `jsonschema` package `urljoin` function is used at some point of reference resolving process - on unix it joins paths correctly, but on windows it behaves differently (there is a disk name, different separators, etc). We need to handle this, luckily only two tests affected (other features work as expected). I'll work on this during the weekend

**Comment by Stranger6667** [comment] 2020-02-14 17:19
@Jonke - thank you for suggesting `prance`, I'll definitely look into resolving implementation there

**Closed** 2020-02-22 13:49 UTC

**Comment by Stranger6667** [comment] 2020-02-22 13:55
Please, check the new `0.24.4` release - https://pypi.org/project/schemathesis/0.24.4/

The error is fixed - now refs are treated proper URI with "file" schema, not OS-specific paths. Feel free to reopen this issue or create a new one if the new release doesn't solve your particular case (CI passes and I tried an example from the description on my Windows machine - everything works). Sorry for inconvenience
