### ISSUE TITLE
Allowing Specific Status Codes Globally

### ISSUE THREAD

**Issue by hatzel** [kiwicom/schemathesis#595] opened 2020-05-20 09:53 UTC
Is there a way to globally allow status codes? 

My specific use case are 415 and 422 responses.
They are well defined but only occur with non-compliant requests. `requests.put('http://127.0.0.1:8080/<path>/)` for example ends up not having a JSON content type which means I return a 415 error.

I'd rather not specify the response codes on every route in the spec, I guess I could write a custom check like `status_code_conformance` and use that instead. I did however come across [this](https://github.com/kiwicom/schemathesis/blob/5b4295652606a787d9b2c11fb7af4feee0ed6295/src/schemathesis/specs/openapi/checks.py#L20-L21) which made we wonder this is somehow already possible/intended to work at some point.

**Comment by Stranger6667** [comment] 2020-05-29 11:03
Hi @hatzel 

Sorry for the late reply. 

I don't see a way to specify responses globally for all operations in a single place in the schema itself. But there are some options that might help:
1. If you use YAML you can use anchors and e.g. define a group of responses, add an anchor and use it in your schema. A good example of it - https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
2. Use references to reuse already defined responses or use `default`. Both options are nicely described [here](https://swagger.io/docs/specification/describing-responses/)
3. Custom check that you mentioned
4. We can create some configuration for Schemathesis that will allow some fine-tuning

From my perspective, the best way is to keep the definitions in the schema (options 1 & 2) and you can minimize repetitions with YAML anchors, the `default` & `$ref` approaches are more verbose. In this way, it will be documented as well and might benefit 3rd party users, but depends, a custom check might be faster/easier to implement. I'd like to implement some configuration at some point and maybe we can have this option configurable, but I don't have it in my working plan for the near future.

Let me know if these options can help with this issue :)

Cheers

**Comment by hatzel** [comment] 2020-06-03 09:23
Thanks for your answer!

I will probably just go with 2.
Given that the errors occur on requests not complying with my specification I think 3 would also be very acceptable. It would be great to have some configuration in schemathesis for this at some point, but there is a reasonable workaround so I would not make it a priority.

I have had YAML anchors break some tooling (specifically [openapi-generator](https://github.com/OpenAPITools/openapi-generator), see [this issue](https://github.com/OpenAPITools/openapi-generator/issues/1593)), so that is something to be aware of for anyone stumbling upon this issue.

**Comment by Stranger6667** [comment] 2020-07-31 18:24
I assume, that the issue is resolved. Feel free to reopen it if you have any additional things to discuss regarding this topic.

> It would be great to have some configuration in schemathesis for this at some point, but there is a reasonable workaround so I would not make it a priority.

I'll consider tuning options after the planned refactoring and will re-check this issue then, but for now, I'd close it

**Closed by Stranger6667** 2020-07-31 18:24 UTC
