### ISSUE TITLE
Response code range not supported

### ISSUE THREAD

**Issue by MissiaL** [kiwicom/schemathesis#330] opened 2019-12-13 09:48 UTC
Thanks for adding check of response code!

Response codes may contain a range of code in the format XXX
https://swagger.io/specification/#responsesObject

My output
```
        if errors:
>           raise AssertionError(*errors)
E           AssertionError: Received a response with a status code, which is not defined in the schema: 404
E           
E           Declared status codes: 4XX, 200
```

**Comment by Stranger6667** [comment] 2019-12-13 10:32
You're welcome :)
Wow, cool - I didn't know about this feature - will implement it soon

**Comment by Stranger6667** [comment] 2019-12-13 13:43
Released in 0.20.1 - https://pypi.org/project/schemathesis/0.20.1/

**Comment by MissiaL** [comment] 2019-12-13 16:02
Still not working
The common problem in your code:

In my tests, I use a fastapi [client](https://fastapi.tiangolo.com/tutorial/testing/) based on an older version `requests`.  In this version `response.status_code` may have a textual representation of the error. For example:
```
response.status_code == HTTPStatus.BAD_REQUEST
```

You should use int status code, not str
```
def status_code_conformance(response: GenericResponse, case: "Case") -> None:
    responses = case.endpoint.definition.get("responses", {})
    # "default" can be used as the default response object for all HTTP codes that are not covered individually
    if "default" in responses:
        return
    allowed_response_statuses = list(map(int, _expand_responses(responses)))
    if int(response.status_code) not in allowed_response_statuses:
        message = (
            f"Received a response with a status code, which is not defined in the schema: "
            f"{response.status_code}\n\nDeclared status codes: {', '.join(allowed_response_statuses)}"
        )
        raise AssertionError(message)

```

**Comment by Stranger6667** [comment] 2019-12-13 16:42
In the current implementation they both casted to string - https://github.com/kiwicom/schemathesis/blob/master/src/schemathesis/checks.py#L28

Since they should be strings on the open api spec side anyway

**Comment by Stranger6667** [comment] 2019-12-13 16:48
However let me check that client you mentioned

**Comment by Stranger6667** [comment] 2019-12-13 16:52
Do you still get the same error with the new version of schemathesis?

**Comment by Stranger6667** [comment] 2019-12-13 17:04
It would be nice to know what version of fastapi / requests you're using and some minimal code to reproduce the error - could you, please, add it? :)

I didn't find any version that has `status_code` as text representation - maybe I am looking in a wrong direction

**Comment by Stranger6667** [comment] 2019-12-13 17:07
Btw, `IntEnum` is comparable with ints, that's why the comparison is true in your example (I assume it is)
```
>>> 400 == HTTPStatus.BAD_REQUEST
True
```

So, it is not a textual representation as far as I can see

**Comment by MissiaL** [comment] 2019-12-17 10:44
Still, the error is in your code. You convert a `response.status_code` to a string, but you need convert to int
```
>>> 400 == str(HTTPStatus.BAD_REQUEST)
```
False

**Comment by Stranger6667** [comment] 2019-12-17 11:10
Aha, now I understand the issue. Would you mind providing `requests` / `fastapi` versions that have `HTTPStatus` instances in `status_code` attribute?

**Comment by Stranger6667** [comment] 2019-12-17 11:14
This one should fix it - #334 
However, it will be nice to have a test case that will cover your case - with package versions I will try to add them

**Comment by Stranger6667** [comment] 2019-12-17 12:30
Pls, check if release `0.20.3` works for you

**Comment by Stranger6667** [comment] 2019-12-19 13:02
@MissiaL 
Feel free to reopen the issue if the problem will occur again

**Closed by Stranger6667** 2019-12-19 13:02 UTC
Labels: Priority: High, Type: Feature
